# sets generator options.
generator:
  # sets generator features.
  features:
    enable:
      # Enables paths server generation
      - 'paths/server'
       # Enables webhooks server generation
      - 'webhooks/server'
      # Enables stub Handler generation
      - 'ogen/unimplemented'
    disable_all: true